on: push
name: Docker build and run
jobs:
  build:
    name: Docker build and run
    if: '!github.event.deleted'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker build
      run: docker build --tag depcheck:latest .
    - name: Run in Docker
      run: docker run -t --rm depcheck:latest help
